[connectivity]
web-listen-endpoints=['127.0.0.1:8443']
enable-quic-frontend=false
web-use-hsts=false

[security]
authentication="none"

[session-management]
create-session=false
enable-gl-in-virtual-sessions="always-off"
